<div class="status-form">
<form class="" action="<?php echo $block->getBaseUrl().'customerattributenew/customer/save'; ?>" id="statusform" method="post">
   <fieldset class="fieldset">
   
   <div class="field name">
           <label class="label" for="name"><span>Status</span></label>
            <div class="control">
                <input name="customstatus" id="customstatus"  title="customstatus" value="" class="input-text" type="text">
            </div>
        </div>
   
    </fieldset>
	
	<div class="actions-toolbar">
        <div class="primary">
            <button id="btnSubmit" type="submit" title="Submit" class="action submit primary">
                <span>Save</span>
            </button>
        </div>
    </div>


</form>

</div>